import { createRequestHandler } from '@react-router/express';
import compression from 'compression';
import express from 'express';
import morgan from 'morgan';

const BUILD_PATH = './build/server/index.js';
const PORT = Number.parseInt(process.env.PORT || '3000');

const app = express();

app.use(compression());
app.disable('x-powered-by');

console.log('Starting production server');

// Serve static assets generated by the React Router build pipeline
app.use(
  '/assets',
  express.static('build/client/assets', { immutable: true, maxAge: '1y' }),
);
app.use(
  '/images',
  express.static('public/images', { immutable: true, maxAge: '1y' }),
);

// Serve static files from public/ — but NOT /sitemap.xml, which is a
// dynamic React Router resource route (routes/sitemap.tsx). The SFTP deploy
// uses delete_remote_files: false, so a stale sitemap.xml from a previous
// deployment may still exist in public/. We wrap express.static so the
// handler is never invoked for that path, forcing the request to fall
// through to the React Router handler below.
const publicStatic = express.static('public', {
  immutable: true,
  maxAge: '1y',
  setHeaders(response, filePath) {
    if (filePath.endsWith('/favicon.svg')) {
      response.setHeader(
        'Cache-Control',
        'public, max-age=31536000, immutable',
      );
    }
  },
});

app.use((req, res, next) => {
  if (req.path === '/sitemap.xml') return next();
  publicStatic(req, res, next);
});
app.use(
  '/fonts',
  express.static('public/fonts', { immutable: true, maxAge: '1y' }),
);

app.use(morgan('tiny'));
// Serve build/client static assets (JS/CSS chunks, etc.) but NEVER serve
// index.html — that would shadow the React Router SSR handler and serve a
// stale <title> from the build template (e.g. "Web App | Monorepo").
// Setting index: false ensures "/" falls through to createRequestHandler.
app.use(express.static('build/client', { maxAge: '1h', index: false }));

// Pass the compiled React Router build into the Express request handler
app.use(
  createRequestHandler({
    build: await import(BUILD_PATH),
  }),
);

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
