import { createRequestHandler } from '@react-router/express';
import compression from 'compression';
import express from 'express';
import morgan from 'morgan';

const BUILD_PATH = './build/server/index.js';
const PORT = Number.parseInt(process.env.PORT || '3000');

const app = express();

app.use(compression());
app.disable('x-powered-by');

console.log('Starting production server');

// Serve static assets generated by the React Router build pipeline
app.use(
  '/assets',
  express.static('build/client/assets', { immutable: true, maxAge: '1y' }),
);
app.use(
  '/images',
  express.static('public/images', { immutable: true, maxAge: '1y' }),
);
app.use('/', express.static('public', { immutable: true, maxAge: '1y' }));
app.use(
  '/fonts',
  express.static('public/fonts', { immutable: true, maxAge: '1y' }),
);

app.use(morgan('tiny'));
app.use(express.static('build/client', { maxAge: '1h' }));

// Pass the compiled React Router build into the Express request handler
app.use(
  createRequestHandler({
    build: await import(BUILD_PATH),
  }),
);

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
